### ISSUE TITLE
Add support for defining embedded methods

### ISSUE THREAD

**Issue by lynndixon** [jnovotni/cloudforms-automate-object-creator#2]
Need the ability to add the path for an embedded method to an inline method type.

**Comment by lynndixon** [comment]
in the methods yaml definition embedded method should like like this as an example:

```
---
object_type: method
version: 1.0
object:
  attributes:
    name: vmware_boot_bios
    display_name:
    description:
    scope: instance
    language: ruby
    location: inline
    embedded_methods:
    - "/StdLib/Core/main"
    - "/StdLib/Core/rbvmomi"
    - "/StdLib/Core/get_vm"
    options: {}
  inputs: []
```
